apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-status
  labels:
    app: http-status
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-status
  template:
    metadata:
      labels:
        app: http-status
    spec:
      containers:
      - name: http-status
        image: ghcr.io/kanja22/http-status:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: http-status  
  labels:
    app: http-status
  namespace: http-status
spec:
  ports:
  - name: web
    port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: http-status
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-status
  namespace: http-status
  labels:
    app: http-status
  annotations:
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - http-status.http-status.cloud.ak-online.be
    secretName: serv-cert
  rules:
  - host: http-status.http-status.cloud.ak-online.be
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: http-status
            port: 
              number: 80
